### ISSUE TITLE
"Downloads" mini-tab empty and shrunk - exception

### ISSUE THREAD

**Issue by zb-z** [puemos/hls-downloader-chrome-extension#54] opened 2020-01-26 09:50 UTC
![HLS_bug_UI_Downloads Tab](https://user-images.githubusercontent.com/28362681/73133389-d230f400-3fdc-11ea-8e95-e08e710b7933.PNG)

The other two are in good state - it did latch on and downloaded and saved an item while in that state but the mini-never recovered as UI - hat to kill extensions process and let Chrome reload it.

Let me copy what I was able to collect from Dev Console.

2.522e8fb2.chunk.js:2 Uncaught TypeError: Cannot read property 'title' of undefined
    at Q (main.129a7291.chunk.js:193)
    at sa (2.522e8fb2.chunk.js:2)
    at Tu (2.522e8fb2.chunk.js:2)
    at ml (2.522e8fb2.chunk.js:2)
    at pl (2.522e8fb2.chunk.js:2)
    at il (2.522e8fb2.chunk.js:2)
    at 2.522e8fb2.chunk.js:2
    at t.unstable_runWithPriority (2.522e8fb2.chunk.js:2)
    at Vo (2.522e8fb2.chunk.js:2)
    at Yo (2.522e8fb2.chunk.js:2)

HTML for chrome-extension://apomkbibleomoihlhhdbeghnfioffbej/downloads

<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
<meta name="theme-color" content="#000000">
<link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
<style data-styled="active" data-styled-version="5.0.0"></style>
</head>
<body>
<noscript>You need to enable JavaScript to run this app.</noscript>
<div id="root">
</div>
<script src="/static/js/runtime-main.25c6d117.js"></script>
<script src="/static/js/2.522e8fb2.chunk.js"></script>
<script src="/static/js/main.129a7291.chunk.js"></script>
</body>
</html>

**Comment by puemos** [comment] 2020-01-26 10:38
Duplicate of #51 
Fixed on v1.7.2 "Pending Release"
Meanwhile: https://github.com/puemos/hls-downloader-chrome-extension/issues/51#issuecomment-577047770

**Closed by puemos** 2020-01-26 10:38 UTC
Labels: bug
